apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-api
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-api
                port:
                  number: 80

